In [27]:
import time
import numpy as np

start_time = time.time()

n = 7

def find3Numbers(A, arr_size, sum):
  triplets = []
  for i in range(0, arr_size-1):
    l = i
    r = arr_size-1
    while (l <= r):   
      if( A[i] + A[l] + A[r] == sum):
        #print("Triplet is", A[i],', ', A[l], ', ', A[r])
        triplets.append([A[i],A[l],A[r]])
        l += 1        
      elif (A[i] + A[l] + A[r] < sum):
        l += 1
      else:
        r -= 1
  return triplets

A = np.arange(n+1)
sum = max(A)
arr_size = len(A)

## TODO: Make it set - or restrictions
triplets = find3Numbers(A, arr_size, sum)
triplets_reel = []
 
for t in triplets:
    triplets_reel.append([t[0],t[1],t[2]])
    
    if t[0]==t[1]==t[2]:
        continue
    
    if t[0]==t[1]:
        triplets_reel.append([t[2],t[1],t[0]])
        triplets_reel.append([t[0],t[2],t[1]])
        continue
    if t[1]==t[2]:   
        triplets_reel.append([t[1],t[0],t[2]])
        triplets_reel.append([t[2],t[1],t[0]])
        continue
        
    if t[0]==t[2]:  
        triplets_reel.append([t[0],t[2],t[1]])
        triplets_reel.append([t[1],t[0],t[2]])
        continue
        
    triplets_reel.append([t[0],t[2],t[1]])    
    triplets_reel.append([t[1],t[2],t[0]])
    triplets_reel.append([t[1],t[0],t[2]])
    triplets_reel.append([t[2],t[0],t[1]])
    triplets_reel.append([t[2],t[1],t[0]])


triplet_list = np.array(triplets_reel)
#print(triplet)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.05013585090637207 seconds ---


In [28]:
len(triplet_list)

36

In [29]:
resulting_list = np.zeros((len(triplet_list)),dtype=bool)
pos_avail_info = np.ones((3,n+1),dtype=bool)

In [30]:
def check_pos(positional_info, triplet):
    return positional_info[0, triplet[0]] and positional_info[1, triplet[1]] and positional_info[2, triplet[2]] 

In [31]:
def update_pos(positional_info, triplet):
    new_pos_info = positional_info.copy()
    new_pos_info[0, triplet[0]] = False
    new_pos_info[1, triplet[1]] = False
    new_pos_info[2, triplet[2]] = False
    return new_pos_info
def update_res_list(res_list, step):
    new_res_list = res_list.copy()
    new_res_list[step]=True
    return new_res_list

In [32]:
def memoize(f):
    memo = {}
    def helper(step, *args):
        if step not in memo:            
            memo[step] = f(step, *args)
        return memo[step]
    return helper

In [33]:
memoized = {}
triplet_list

array([[0, 0, 7],
       [7, 0, 0],
       [0, 7, 0],
       [0, 1, 6],
       [0, 6, 1],
       [1, 6, 0],
       [1, 0, 6],
       [6, 0, 1],
       [6, 1, 0],
       [0, 2, 5],
       [0, 5, 2],
       [2, 5, 0],
       [2, 0, 5],
       [5, 0, 2],
       [5, 2, 0],
       [0, 3, 4],
       [0, 4, 3],
       [3, 4, 0],
       [3, 0, 4],
       [4, 0, 3],
       [4, 3, 0],
       [1, 1, 5],
       [5, 1, 1],
       [1, 5, 1],
       [1, 2, 4],
       [1, 4, 2],
       [2, 4, 1],
       [2, 1, 4],
       [4, 1, 2],
       [4, 2, 1],
       [1, 3, 3],
       [3, 1, 3],
       [3, 3, 1],
       [2, 2, 3],
       [3, 2, 2],
       [2, 3, 2]])

In [34]:
# TODO: global vs local triplet_list
def recursive_dp(current_step, positional_info, triplet_list, resulting_list):
    current_triplet = triplet_list[current_step]
    #print(positional_info)
    if current_step == 0:
        return  0, resulting_list
    if not check_pos(positional_info, current_triplet):
        return recursive_dp(current_step - 1, positional_info.copy(), triplet_list, resulting_list)
    
    no_update_size, no_update_result = recursive_dp(current_step - 1, positional_info.copy(), triplet_list, resulting_list) 
    update_size, update_result = recursive_dp(current_step - 1, update_pos(positional_info, current_triplet), triplet_list, update_res_list(resulting_list, current_step))
    update_size += 1
    
    if no_update_size < update_size:
        return update_size, update_result
    return no_update_size, no_update_result

In [35]:
start_time = time.time()
num, res = recursive_dp(len(triplet_list)-1,pos_avail_info,triplet_list,resulting_list)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.06795692443847656 seconds ---


In [36]:
triplet_list

array([[0, 0, 7],
       [7, 0, 0],
       [0, 7, 0],
       [0, 1, 6],
       [0, 6, 1],
       [1, 6, 0],
       [1, 0, 6],
       [6, 0, 1],
       [6, 1, 0],
       [0, 2, 5],
       [0, 5, 2],
       [2, 5, 0],
       [2, 0, 5],
       [5, 0, 2],
       [5, 2, 0],
       [0, 3, 4],
       [0, 4, 3],
       [3, 4, 0],
       [3, 0, 4],
       [4, 0, 3],
       [4, 3, 0],
       [1, 1, 5],
       [5, 1, 1],
       [1, 5, 1],
       [1, 2, 4],
       [1, 4, 2],
       [2, 4, 1],
       [2, 1, 4],
       [4, 1, 2],
       [4, 2, 1],
       [1, 3, 3],
       [3, 1, 3],
       [3, 3, 1],
       [2, 2, 3],
       [3, 2, 2],
       [2, 3, 2]])

In [37]:
triplet_list[res]

array([[0, 5, 2],
       [2, 0, 5],
       [3, 4, 0],
       [5, 1, 1],
       [1, 2, 4]])

In [30]:
num

7

In [31]:
mem = memoize(recursive_dp)

In [32]:
start_time = time.time()
num, res = mem(len(triplet_list)-1,pos_avail_info,triplet_list,resulting_list)
print("--- %s seconds ---" % (time.time() - start_time))

--- 4.669327974319458 seconds ---


In [33]:
triplet_list[res]

array([[0, 3, 7],
       [6, 0, 4],
       [5, 5, 0],
       [7, 1, 2],
       [3, 6, 1],
       [1, 4, 5],
       [2, 2, 6]])